### ISSUE TITLE
The JSON child key discrepancies!

### ISSUE THREAD

**Issue by pctn0007** [pctn0007/Motus#2]
When uploading new motion detection meta data to the real-time database, it adds "Picture" key child to store image capture during mType 1 (i.e. external movement), BUT adds "uPicture" key child to store image capture during mType 0 (i.e. case movement).

Fix: Change hardcoded string "uPicture" in Python hardware code/files to "Picture" (both must match in orde to fetch images from storage successfully).

**Comment by BlueDaroosh** [comment]
I'm working on it right now.

**Comment by BlueDaroosh** [comment]
The change has been applied. We need to clear something up first.
Reference the Database in the Firebase to understand this:

Detections:
BoxID: This is the id assigned to the box. This is what helps the app identify what box is yours.
Date: The date when the security discrepancy occurred.  No problems here.
Picture: Changed from uPicture. The name of the image to display. No problems here.
SType: The security type. The app checks this value to determine how the system was triggered.

Users:
boxid: What the app uses to check if a security issue is related to the paired box. rename to "BoxID".
           This is what is asked for from the user during creation of a new account.
email: No problems here. Just an email.
fullname: No problems here. Just a Name.

Update and Change requests: Anthony P.
In the app, ensure upon registration, the user inputs their box ID. This should be saved under the field "BoxID". Make sure to rename that field. Also, the "uPicture field" has been changed to "Picture" Ensure that this works properly now, and the images can be obtained. Otherwise, once everything is all good, you can close the issue. Otherwise, if more changes are needed, let me know.

**Comment by pctn0007** [comment]
Wait did you change other json keys other than "Picture" to different
names? If so, I need to see specific ones because I then have to change it
java.

**Comment by BlueDaroosh** [comment]
My comment above indicates Exaclty what is in the firebase, and what needs to be changed. Ill simplify it for you:

Under users, change "boxid" -> "BoxID" in the java. Capitals just make the thing look better...
Also make sure that when creating a new account, it asks for the BoxID, or be able to change the BoxID under settings at any time.

**Comment by pctn0007** [comment]
Okay cool. Dont change any others though because I have to then manually
change it all in java and then delete all entries in the database to
prevent crashing during tests

**Comment by BlueDaroosh** [comment]
Once you confirm everything works, you can close the issue.
